/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate001.geometry}
        material={materials['Plate.002']}
        position={[-0.0066, 0.79908, 0.27655]}
        rotation={[Math.PI, -0.00407, Math.PI]}
        scale={[0.75712, 0.51371, 0.70803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate.geometry}
        material={materials.Plate}
        position={[-0.0066, 0.79908, 0.27655]}
        rotation={[Math.PI, -0.00407, Math.PI]}
        scale={[0.75712, 0.51371, 0.70803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Plate}
        position={[-0.00559, 0.92555, 0.52544]}
        rotation={[0, 0.00407, -Math.PI]}
        scale={[1, 0.29904, 0.78466]}
      />
      <group
        position={[0.59477, 0.46537, 0.58502]}
        rotation={[Math.PI, -0.78947, Math.PI]}
        scale={[0.88647, 0.98476, 0.96904]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_1.geometry}
          material={materials.Metal}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_cover010.geometry}
        material={materials['table leg mat.001']}
        position={[-0.00526, 0.61442, 0.60666]}
        rotation={[0, -1.56674, 0]}
        scale={[1, 1.11125, 1.35219]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_cover009.geometry}
        material={materials['table leg mat.024']}
        position={[-0.15272, 0.77463, 0.58953]}
        rotation={[0, -1.56674, 0]}
        scale={[1, 1.11125, 1.35219]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_cover008.geometry}
        material={materials['table leg mat.024']}
        position={[0.14206, 0.77463, 0.58834]}
        rotation={[0, -1.56674, 0]}
        scale={[1, 1.11125, 1.35219]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_cover007.geometry}
        material={materials['table leg mat.024']}
        position={[-0.32219, 0.8662, 0.57234]}
        rotation={[0, -1.56674, 0]}
        scale={[1, 1.11125, 3.42886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_cover006.geometry}
        material={materials['table leg mat.024']}
        position={[0.31668, 0.8662, 0.56975]}
        rotation={[0, -1.56674, 0]}
        scale={[1, 1.11125, 3.42886]}
      />
    </group>
  )
}

useGLTF.preload('/Table.glb')

